[workspace]
members = [
    "crates/codspeed",
    "crates/bencher_compat",
    "crates/criterion_compat",
    "crates/cargo-codspeed",
    "crates/divan_compat",
    "crates/divan_compat/macros",
]
resolver = "2"
