[package]
name = "cargo-codspeed"
version = "2.5.1"
edition = "2021"
description = "Cargo extension to build & run your codspeed benchmarks"
authors = ["Arthur Pastel <arthur@codspeed.io>"]
documentation = "https://docs.codspeed.io"
readme = "README.md"
repository = "https://github.com/CodSpeedHQ/codspeed-rust"
homepage = "https://codspeed.io"
license = "MIT OR Apache-2.0"
categories = [
    "development-tools",
    "development-tools::cargo-plugins",
    "development-tools::profiling",
    "development-tools::testing",
]
keywords = ["codspeed", "benchmark", "cargo"]

[dependencies]
cargo = "0.78.1"
clap = { version = "=4.5.4", features = ["derive"] }
termcolor = "1.0"
anyhow = "1.0.66"
itertools = "0.10.5"
anstyle = "1.0.6"

[dev-dependencies]
assert_cmd = "2.0.7"
fs_extra = "1.2.0"
predicates = "2.1.4"
uuid = { version = "1.2.2", features = ["v4"] }

[features]
vendored-openssl = ["cargo/vendored-openssl"]
